// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/crypto_api.dart';
import 'api/transaction_api.dart';
import 'api/wallet_api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 1759413611;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'unvault_core',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<(int, int, int)> crateApiCryptoApiCalibrateArgon2({
    required BigInt targetMinMs,
    required BigInt targetMaxMs,
  });

  Future<WalletCreationResponse> crateApiWalletApiCreateWallet({
    required List<int> password,
    required int wordCount,
  });

  Uint8List crateApiCryptoApiDecrypt({
    required List<int> key,
    required List<int> ciphertext,
  });

  Future<Uint8List> crateApiWalletApiDecryptMnemonic({
    required List<int> password,
    required List<int> encryptedMnemonic,
    required List<int> salt,
    required int memoryKib,
    required int iterations,
    required int parallelism,
  });

  List<String> crateApiWalletApiDeriveAccounts({
    required List<int> phraseBytes,
    required int count,
  });

  Future<Uint8List> crateApiCryptoApiDeriveKey({
    required List<int> password,
    required List<int> salt,
    required int memoryKib,
    required int iterations,
    required int parallelism,
  });

  Future<Uint8List> crateApiCryptoApiDeriveSeed({
    required List<int> phraseBytes,
    required List<int> passphrase,
  });

  Uint8List crateApiCryptoApiEncrypt({
    required List<int> key,
    required List<int> plaintext,
  });

  Uint8List crateApiCryptoApiGenerateMnemonic({required int wordCount});

  Uint8List crateApiCryptoApiGenerateSalt();

  Future<WalletImportResponse> crateApiWalletApiImportWallet({
    required List<int> phraseBytes,
    required List<int> password,
  });

  Future<SignTransactionResponse> crateApiTransactionApiSignTransaction({
    required List<int> privateKey,
    required BigInt chainId,
    required BigInt nonce,
    required String to,
    required String valueWei,
    required List<int> input,
    required BigInt gasLimit,
    required BigInt maxFeePerGas,
    required BigInt maxPriorityFeePerGas,
  });

  Future<SignTransactionResponse>
  crateApiTransactionApiSignTransactionWithSeed({
    required List<int> phraseBytes,
    required int accountIndex,
    required BigInt chainId,
    required BigInt nonce,
    required String to,
    required String valueWei,
    required List<int> input,
    required BigInt gasLimit,
    required BigInt maxFeePerGas,
    required BigInt maxPriorityFeePerGas,
  });

  bool crateApiCryptoApiValidateMnemonic({required List<int> phraseBytes});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<(int, int, int)> crateApiCryptoApiCalibrateArgon2({
    required BigInt targetMinMs,
    required BigInt targetMaxMs,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(targetMinMs, serializer);
          sse_encode_u_64(targetMaxMs, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_record_u_32_u_32_u_32,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCryptoApiCalibrateArgon2ConstMeta,
        argValues: [targetMinMs, targetMaxMs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCryptoApiCalibrateArgon2ConstMeta =>
      const TaskConstMeta(
        debugName: "calibrate_argon2",
        argNames: ["targetMinMs", "targetMaxMs"],
      );

  @override
  Future<WalletCreationResponse> crateApiWalletApiCreateWallet({
    required List<int> password,
    required int wordCount,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(password, serializer);
          sse_encode_u_8(wordCount, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_wallet_creation_response,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiWalletApiCreateWalletConstMeta,
        argValues: [password, wordCount],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWalletApiCreateWalletConstMeta =>
      const TaskConstMeta(
        debugName: "create_wallet",
        argNames: ["password", "wordCount"],
      );

  @override
  Uint8List crateApiCryptoApiDecrypt({
    required List<int> key,
    required List<int> ciphertext,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(key, serializer);
          sse_encode_list_prim_u_8_loose(ciphertext, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCryptoApiDecryptConstMeta,
        argValues: [key, ciphertext],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCryptoApiDecryptConstMeta => const TaskConstMeta(
    debugName: "decrypt",
    argNames: ["key", "ciphertext"],
  );

  @override
  Future<Uint8List> crateApiWalletApiDecryptMnemonic({
    required List<int> password,
    required List<int> encryptedMnemonic,
    required List<int> salt,
    required int memoryKib,
    required int iterations,
    required int parallelism,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(password, serializer);
          sse_encode_list_prim_u_8_loose(encryptedMnemonic, serializer);
          sse_encode_list_prim_u_8_loose(salt, serializer);
          sse_encode_u_32(memoryKib, serializer);
          sse_encode_u_32(iterations, serializer);
          sse_encode_u_32(parallelism, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiWalletApiDecryptMnemonicConstMeta,
        argValues: [
          password,
          encryptedMnemonic,
          salt,
          memoryKib,
          iterations,
          parallelism,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWalletApiDecryptMnemonicConstMeta =>
      const TaskConstMeta(
        debugName: "decrypt_mnemonic",
        argNames: [
          "password",
          "encryptedMnemonic",
          "salt",
          "memoryKib",
          "iterations",
          "parallelism",
        ],
      );

  @override
  List<String> crateApiWalletApiDeriveAccounts({
    required List<int> phraseBytes,
    required int count,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(phraseBytes, serializer);
          sse_encode_u_32(count, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiWalletApiDeriveAccountsConstMeta,
        argValues: [phraseBytes, count],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWalletApiDeriveAccountsConstMeta =>
      const TaskConstMeta(
        debugName: "derive_accounts",
        argNames: ["phraseBytes", "count"],
      );

  @override
  Future<Uint8List> crateApiCryptoApiDeriveKey({
    required List<int> password,
    required List<int> salt,
    required int memoryKib,
    required int iterations,
    required int parallelism,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(password, serializer);
          sse_encode_list_prim_u_8_loose(salt, serializer);
          sse_encode_u_32(memoryKib, serializer);
          sse_encode_u_32(iterations, serializer);
          sse_encode_u_32(parallelism, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCryptoApiDeriveKeyConstMeta,
        argValues: [password, salt, memoryKib, iterations, parallelism],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCryptoApiDeriveKeyConstMeta => const TaskConstMeta(
    debugName: "derive_key",
    argNames: ["password", "salt", "memoryKib", "iterations", "parallelism"],
  );

  @override
  Future<Uint8List> crateApiCryptoApiDeriveSeed({
    required List<int> phraseBytes,
    required List<int> passphrase,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(phraseBytes, serializer);
          sse_encode_list_prim_u_8_loose(passphrase, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCryptoApiDeriveSeedConstMeta,
        argValues: [phraseBytes, passphrase],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCryptoApiDeriveSeedConstMeta =>
      const TaskConstMeta(
        debugName: "derive_seed",
        argNames: ["phraseBytes", "passphrase"],
      );

  @override
  Uint8List crateApiCryptoApiEncrypt({
    required List<int> key,
    required List<int> plaintext,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(key, serializer);
          sse_encode_list_prim_u_8_loose(plaintext, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCryptoApiEncryptConstMeta,
        argValues: [key, plaintext],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCryptoApiEncryptConstMeta =>
      const TaskConstMeta(debugName: "encrypt", argNames: ["key", "plaintext"]);

  @override
  Uint8List crateApiCryptoApiGenerateMnemonic({required int wordCount}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_8(wordCount, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCryptoApiGenerateMnemonicConstMeta,
        argValues: [wordCount],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCryptoApiGenerateMnemonicConstMeta =>
      const TaskConstMeta(
        debugName: "generate_mnemonic",
        argNames: ["wordCount"],
      );

  @override
  Uint8List crateApiCryptoApiGenerateSalt() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCryptoApiGenerateSaltConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCryptoApiGenerateSaltConstMeta =>
      const TaskConstMeta(debugName: "generate_salt", argNames: []);

  @override
  Future<WalletImportResponse> crateApiWalletApiImportWallet({
    required List<int> phraseBytes,
    required List<int> password,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(phraseBytes, serializer);
          sse_encode_list_prim_u_8_loose(password, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_wallet_import_response,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiWalletApiImportWalletConstMeta,
        argValues: [phraseBytes, password],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWalletApiImportWalletConstMeta =>
      const TaskConstMeta(
        debugName: "import_wallet",
        argNames: ["phraseBytes", "password"],
      );

  @override
  Future<SignTransactionResponse> crateApiTransactionApiSignTransaction({
    required List<int> privateKey,
    required BigInt chainId,
    required BigInt nonce,
    required String to,
    required String valueWei,
    required List<int> input,
    required BigInt gasLimit,
    required BigInt maxFeePerGas,
    required BigInt maxPriorityFeePerGas,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(privateKey, serializer);
          sse_encode_u_64(chainId, serializer);
          sse_encode_u_64(nonce, serializer);
          sse_encode_String(to, serializer);
          sse_encode_String(valueWei, serializer);
          sse_encode_list_prim_u_8_loose(input, serializer);
          sse_encode_u_64(gasLimit, serializer);
          sse_encode_U128(maxFeePerGas, serializer);
          sse_encode_U128(maxPriorityFeePerGas, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_sign_transaction_response,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiTransactionApiSignTransactionConstMeta,
        argValues: [
          privateKey,
          chainId,
          nonce,
          to,
          valueWei,
          input,
          gasLimit,
          maxFeePerGas,
          maxPriorityFeePerGas,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTransactionApiSignTransactionConstMeta =>
      const TaskConstMeta(
        debugName: "sign_transaction",
        argNames: [
          "privateKey",
          "chainId",
          "nonce",
          "to",
          "valueWei",
          "input",
          "gasLimit",
          "maxFeePerGas",
          "maxPriorityFeePerGas",
        ],
      );

  @override
  Future<SignTransactionResponse>
  crateApiTransactionApiSignTransactionWithSeed({
    required List<int> phraseBytes,
    required int accountIndex,
    required BigInt chainId,
    required BigInt nonce,
    required String to,
    required String valueWei,
    required List<int> input,
    required BigInt gasLimit,
    required BigInt maxFeePerGas,
    required BigInt maxPriorityFeePerGas,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(phraseBytes, serializer);
          sse_encode_u_32(accountIndex, serializer);
          sse_encode_u_64(chainId, serializer);
          sse_encode_u_64(nonce, serializer);
          sse_encode_String(to, serializer);
          sse_encode_String(valueWei, serializer);
          sse_encode_list_prim_u_8_loose(input, serializer);
          sse_encode_u_64(gasLimit, serializer);
          sse_encode_U128(maxFeePerGas, serializer);
          sse_encode_U128(maxPriorityFeePerGas, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_sign_transaction_response,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiTransactionApiSignTransactionWithSeedConstMeta,
        argValues: [
          phraseBytes,
          accountIndex,
          chainId,
          nonce,
          to,
          valueWei,
          input,
          gasLimit,
          maxFeePerGas,
          maxPriorityFeePerGas,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTransactionApiSignTransactionWithSeedConstMeta =>
      const TaskConstMeta(
        debugName: "sign_transaction_with_seed",
        argNames: [
          "phraseBytes",
          "accountIndex",
          "chainId",
          "nonce",
          "to",
          "valueWei",
          "input",
          "gasLimit",
          "maxFeePerGas",
          "maxPriorityFeePerGas",
        ],
      );

  @override
  bool crateApiCryptoApiValidateMnemonic({required List<int> phraseBytes}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(phraseBytes, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCryptoApiValidateMnemonicConstMeta,
        argValues: [phraseBytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCryptoApiValidateMnemonicConstMeta =>
      const TaskConstMeta(
        debugName: "validate_mnemonic",
        argNames: ["phraseBytes"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  BigInt dco_decode_U128(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return BigInt.parse(raw);
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  (int, int, int) dco_decode_record_u_32_u_32_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3) {
      throw Exception('Expected 3 elements, got ${arr.length}');
    }
    return (
      dco_decode_u_32(arr[0]),
      dco_decode_u_32(arr[1]),
      dco_decode_u_32(arr[2]),
    );
  }

  @protected
  SignTransactionResponse dco_decode_sign_transaction_response(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return SignTransactionResponse(
      rawTx: dco_decode_list_prim_u_8_strict(arr[0]),
      txHash: dco_decode_list_prim_u_8_strict(arr[1]),
      from: dco_decode_String(arr[2]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  WalletCreationResponse dco_decode_wallet_creation_response(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return WalletCreationResponse(
      encryptedMnemonic: dco_decode_list_prim_u_8_strict(arr[0]),
      salt: dco_decode_list_prim_u_8_strict(arr[1]),
      argon2MemoryKib: dco_decode_u_32(arr[2]),
      argon2Iterations: dco_decode_u_32(arr[3]),
      argon2Parallelism: dco_decode_u_32(arr[4]),
      firstAddress: dco_decode_String(arr[5]),
      mnemonicBytes: dco_decode_list_prim_u_8_strict(arr[6]),
    );
  }

  @protected
  WalletImportResponse dco_decode_wallet_import_response(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return WalletImportResponse(
      encryptedMnemonic: dco_decode_list_prim_u_8_strict(arr[0]),
      salt: dco_decode_list_prim_u_8_strict(arr[1]),
      argon2MemoryKib: dco_decode_u_32(arr[2]),
      argon2Iterations: dco_decode_u_32(arr[3]),
      argon2Parallelism: dco_decode_u_32(arr[4]),
      firstAddress: dco_decode_String(arr[5]),
    );
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  BigInt sse_decode_U128(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return BigInt.parse(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  (int, int, int) sse_decode_record_u_32_u_32_u_32(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_u_32(deserializer);
    var var_field1 = sse_decode_u_32(deserializer);
    var var_field2 = sse_decode_u_32(deserializer);
    return (var_field0, var_field1, var_field2);
  }

  @protected
  SignTransactionResponse sse_decode_sign_transaction_response(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_rawTx = sse_decode_list_prim_u_8_strict(deserializer);
    var var_txHash = sse_decode_list_prim_u_8_strict(deserializer);
    var var_from = sse_decode_String(deserializer);
    return SignTransactionResponse(
      rawTx: var_rawTx,
      txHash: var_txHash,
      from: var_from,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  WalletCreationResponse sse_decode_wallet_creation_response(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_encryptedMnemonic = sse_decode_list_prim_u_8_strict(deserializer);
    var var_salt = sse_decode_list_prim_u_8_strict(deserializer);
    var var_argon2MemoryKib = sse_decode_u_32(deserializer);
    var var_argon2Iterations = sse_decode_u_32(deserializer);
    var var_argon2Parallelism = sse_decode_u_32(deserializer);
    var var_firstAddress = sse_decode_String(deserializer);
    var var_mnemonicBytes = sse_decode_list_prim_u_8_strict(deserializer);
    return WalletCreationResponse(
      encryptedMnemonic: var_encryptedMnemonic,
      salt: var_salt,
      argon2MemoryKib: var_argon2MemoryKib,
      argon2Iterations: var_argon2Iterations,
      argon2Parallelism: var_argon2Parallelism,
      firstAddress: var_firstAddress,
      mnemonicBytes: var_mnemonicBytes,
    );
  }

  @protected
  WalletImportResponse sse_decode_wallet_import_response(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_encryptedMnemonic = sse_decode_list_prim_u_8_strict(deserializer);
    var var_salt = sse_decode_list_prim_u_8_strict(deserializer);
    var var_argon2MemoryKib = sse_decode_u_32(deserializer);
    var var_argon2Iterations = sse_decode_u_32(deserializer);
    var var_argon2Parallelism = sse_decode_u_32(deserializer);
    var var_firstAddress = sse_decode_String(deserializer);
    return WalletImportResponse(
      encryptedMnemonic: var_encryptedMnemonic,
      salt: var_salt,
      argon2MemoryKib: var_argon2MemoryKib,
      argon2Iterations: var_argon2Iterations,
      argon2Parallelism: var_argon2Parallelism,
      firstAddress: var_firstAddress,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_U128(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.toString(), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_record_u_32_u_32_u_32(
    (int, int, int) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.$1, serializer);
    sse_encode_u_32(self.$2, serializer);
    sse_encode_u_32(self.$3, serializer);
  }

  @protected
  void sse_encode_sign_transaction_response(
    SignTransactionResponse self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.rawTx, serializer);
    sse_encode_list_prim_u_8_strict(self.txHash, serializer);
    sse_encode_String(self.from, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_wallet_creation_response(
    WalletCreationResponse self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.encryptedMnemonic, serializer);
    sse_encode_list_prim_u_8_strict(self.salt, serializer);
    sse_encode_u_32(self.argon2MemoryKib, serializer);
    sse_encode_u_32(self.argon2Iterations, serializer);
    sse_encode_u_32(self.argon2Parallelism, serializer);
    sse_encode_String(self.firstAddress, serializer);
    sse_encode_list_prim_u_8_strict(self.mnemonicBytes, serializer);
  }

  @protected
  void sse_encode_wallet_import_response(
    WalletImportResponse self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.encryptedMnemonic, serializer);
    sse_encode_list_prim_u_8_strict(self.salt, serializer);
    sse_encode_u_32(self.argon2MemoryKib, serializer);
    sse_encode_u_32(self.argon2Iterations, serializer);
    sse_encode_u_32(self.argon2Parallelism, serializer);
    sse_encode_String(self.firstAddress, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
