// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Generates a new BIP-39 mnemonic and returns it as bytes.
///
/// `word_count`: 12 or 24.
///
/// Returns: mnemonic phrase as UTF-8 bytes (space-separated words).
///
/// SECURITY: The caller receives raw bytes — must be zeroized after use on the Dart side.
Uint8List generateMnemonic({required int wordCount}) => RustLib.instance.api
    .crateApiCryptoApiGenerateMnemonic(wordCount: wordCount);

/// Validates a BIP-39 mnemonic phrase.
///
/// `phrase_bytes`: mnemonic phrase as UTF-8 bytes.
///
/// Returns: `true` if valid.
bool validateMnemonic({required List<int> phraseBytes}) => RustLib.instance.api
    .crateApiCryptoApiValidateMnemonic(phraseBytes: phraseBytes);

/// Derives a 64-byte BIP-39 seed from a mnemonic phrase and optional passphrase.
///
/// Both inputs are byte slices — NEVER String.
///
/// Returns: 64-byte seed.
Future<Uint8List> deriveSeed({
  required List<int> phraseBytes,
  required List<int> passphrase,
}) => RustLib.instance.api.crateApiCryptoApiDeriveSeed(
  phraseBytes: phraseBytes,
  passphrase: passphrase,
);

/// Generates a random 16-byte salt for Argon2id.
Uint8List generateSalt() =>
    RustLib.instance.api.crateApiCryptoApiGenerateSalt();

/// Derives a 32-byte encryption key from password + salt via Argon2id.
///
/// `password`: password as bytes.
/// `salt`: 16-byte salt.
/// `memory_kib`, `iterations`, `parallelism`: Argon2id parameters.
///
/// Returns: 32-byte derived key.
Future<Uint8List> deriveKey({
  required List<int> password,
  required List<int> salt,
  required int memoryKib,
  required int iterations,
  required int parallelism,
}) => RustLib.instance.api.crateApiCryptoApiDeriveKey(
  password: password,
  salt: salt,
  memoryKib: memoryKib,
  iterations: iterations,
  parallelism: parallelism,
);

/// Calibrates Argon2id parameters for the current device.
///
/// Returns: (memory_kib, iterations, parallelism).
Future<(int, int, int)> calibrateArgon2({
  required BigInt targetMinMs,
  required BigInt targetMaxMs,
}) => RustLib.instance.api.crateApiCryptoApiCalibrateArgon2(
  targetMinMs: targetMinMs,
  targetMaxMs: targetMaxMs,
);

/// Encrypts data with AES-256-GCM.
///
/// `key`: 32-byte encryption key.
/// `plaintext`: data to encrypt.
///
/// Returns: `nonce(12) || ciphertext || tag(16)`.
Uint8List encrypt({required List<int> key, required List<int> plaintext}) =>
    RustLib.instance.api.crateApiCryptoApiEncrypt(
      key: key,
      plaintext: plaintext,
    );

/// Decrypts data with AES-256-GCM.
///
/// `key`: 32-byte encryption key.
/// `ciphertext`: data as produced by `encrypt`.
///
/// Returns: decrypted plaintext bytes.
Uint8List decrypt({required List<int> key, required List<int> ciphertext}) =>
    RustLib.instance.api.crateApiCryptoApiDecrypt(
      key: key,
      ciphertext: ciphertext,
    );
