// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Builds and signs an EIP-1559 transaction.
///
/// SECURITY: The `private_key` is consumed by this function and used only for signing.
/// The signed raw transaction is returned — the private key never crosses back to Dart.
///
/// # Parameters
/// - `private_key`: 32-byte private key as bytes.
/// - `chain_id`: EIP-155 chain ID.
/// - `nonce`: sender's current nonce.
/// - `to`: recipient address as hex string (with 0x prefix), or empty for contract creation.
/// - `value_wei`: value in wei as a decimal string (to avoid overflow with u64).
/// - `input`: calldata bytes.
/// - `gas_limit`: gas limit.
/// - `max_fee_per_gas`: max fee per gas in wei.
/// - `max_priority_fee_per_gas`: max priority fee per gas in wei.
///
/// # Returns
/// `SignTransactionResponse` with raw tx bytes, tx hash, and sender address.
Future<SignTransactionResponse> signTransaction({
  required List<int> privateKey,
  required BigInt chainId,
  required BigInt nonce,
  required String to,
  required String valueWei,
  required List<int> input,
  required BigInt gasLimit,
  required BigInt maxFeePerGas,
  required BigInt maxPriorityFeePerGas,
}) => RustLib.instance.api.crateApiTransactionApiSignTransaction(
  privateKey: privateKey,
  chainId: chainId,
  nonce: nonce,
  to: to,
  valueWei: valueWei,
  input: input,
  gasLimit: gasLimit,
  maxFeePerGas: maxFeePerGas,
  maxPriorityFeePerGas: maxPriorityFeePerGas,
);

/// Response from signing a transaction.
class SignTransactionResponse {
  /// RLP-encoded signed transaction bytes (ready for `eth_sendRawTransaction`).
  final Uint8List rawTx;

  /// Transaction hash (32 bytes).
  final Uint8List txHash;

  /// Sender address (EIP-55 checksummed, non-sensitive).
  final String from;

  const SignTransactionResponse({
    required this.rawTx,
    required this.txHash,
    required this.from,
  });

  @override
  int get hashCode => rawTx.hashCode ^ txHash.hashCode ^ from.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SignTransactionResponse &&
          runtimeType == other.runtimeType &&
          rawTx == other.rawTx &&
          txHash == other.txHash &&
          from == other.from;
}
