// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Creates a new wallet.
///
/// `password`: password as bytes (≥8 chars enforced at Dart layer).
/// `word_count`: 12 or 24.
///
/// Returns: (encrypted_mnemonic, salt, argon2_memory, argon2_iterations, argon2_parallelism,
///           first_address, mnemonic_bytes)
///
/// SECURITY: `mnemonic_bytes` is returned for backup display. Dart must zeroize after use.
Future<WalletCreationResponse> createWallet({
  required List<int> password,
  required int wordCount,
}) => RustLib.instance.api.crateApiWalletApiCreateWallet(
  password: password,
  wordCount: wordCount,
);

/// Imports a wallet from an existing mnemonic phrase.
///
/// `phrase_bytes`: mnemonic as UTF-8 bytes.
/// `password`: password as bytes.
///
/// Returns: encrypted mnemonic + metadata.
Future<WalletImportResponse> importWallet({
  required List<int> phraseBytes,
  required List<int> password,
}) => RustLib.instance.api.crateApiWalletApiImportWallet(
  phraseBytes: phraseBytes,
  password: password,
);

/// Decrypts and returns the mnemonic phrase for backup verification.
///
/// SECURITY: Returned bytes must be zeroized by caller after display.
Future<Uint8List> decryptMnemonic({
  required List<int> password,
  required List<int> encryptedMnemonic,
  required List<int> salt,
  required int memoryKib,
  required int iterations,
  required int parallelism,
}) => RustLib.instance.api.crateApiWalletApiDecryptMnemonic(
  password: password,
  encryptedMnemonic: encryptedMnemonic,
  salt: salt,
  memoryKib: memoryKib,
  iterations: iterations,
  parallelism: parallelism,
);

/// Derives Ethereum account addresses from a mnemonic.
///
/// `phrase_bytes`: mnemonic as UTF-8 bytes.
/// `count`: number of accounts to derive (0-based sequential).
///
/// Returns: list of EIP-55 checksummed addresses (non-sensitive, safe as String).
List<String> deriveAccounts({
  required List<int> phraseBytes,
  required int count,
}) => RustLib.instance.api.crateApiWalletApiDeriveAccounts(
  phraseBytes: phraseBytes,
  count: count,
);

/// Response from wallet creation — all data needed for storage and display.
class WalletCreationResponse {
  /// Encrypted mnemonic (nonce || ciphertext || tag).
  final Uint8List encryptedMnemonic;

  /// 16-byte Argon2id salt.
  final Uint8List salt;

  /// Argon2id memory cost in KiB.
  final int argon2MemoryKib;

  /// Argon2id iterations.
  final int argon2Iterations;

  /// Argon2id parallelism.
  final int argon2Parallelism;

  /// First derived address (EIP-55 checksummed, non-sensitive).
  final String firstAddress;

  /// Mnemonic phrase as bytes — MUST be zeroized by caller after backup display.
  final Uint8List mnemonicBytes;

  const WalletCreationResponse({
    required this.encryptedMnemonic,
    required this.salt,
    required this.argon2MemoryKib,
    required this.argon2Iterations,
    required this.argon2Parallelism,
    required this.firstAddress,
    required this.mnemonicBytes,
  });

  @override
  int get hashCode =>
      encryptedMnemonic.hashCode ^
      salt.hashCode ^
      argon2MemoryKib.hashCode ^
      argon2Iterations.hashCode ^
      argon2Parallelism.hashCode ^
      firstAddress.hashCode ^
      mnemonicBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WalletCreationResponse &&
          runtimeType == other.runtimeType &&
          encryptedMnemonic == other.encryptedMnemonic &&
          salt == other.salt &&
          argon2MemoryKib == other.argon2MemoryKib &&
          argon2Iterations == other.argon2Iterations &&
          argon2Parallelism == other.argon2Parallelism &&
          firstAddress == other.firstAddress &&
          mnemonicBytes == other.mnemonicBytes;
}

/// Response from wallet import.
class WalletImportResponse {
  final Uint8List encryptedMnemonic;
  final Uint8List salt;
  final int argon2MemoryKib;
  final int argon2Iterations;
  final int argon2Parallelism;
  final String firstAddress;

  const WalletImportResponse({
    required this.encryptedMnemonic,
    required this.salt,
    required this.argon2MemoryKib,
    required this.argon2Iterations,
    required this.argon2Parallelism,
    required this.firstAddress,
  });

  @override
  int get hashCode =>
      encryptedMnemonic.hashCode ^
      salt.hashCode ^
      argon2MemoryKib.hashCode ^
      argon2Iterations.hashCode ^
      argon2Parallelism.hashCode ^
      firstAddress.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WalletImportResponse &&
          runtimeType == other.runtimeType &&
          encryptedMnemonic == other.encryptedMnemonic &&
          salt == other.salt &&
          argon2MemoryKib == other.argon2MemoryKib &&
          argon2Iterations == other.argon2Iterations &&
          argon2Parallelism == other.argon2Parallelism &&
          firstAddress == other.firstAddress;
}
